version: 0.2
run-as: root


phases:
  pre_build:
    commands:
      - echo install nginx
      - yum install nginx -y && systemctl enable nginx && systemctl start nginx
      - curl -I http://localhost
      - if [ $(echo $?) -eq 0 ] ; then echo OK; fi
  build:
    commands:
      - echo update site
      - cp index.html > /var/wwww/html/
